[features]
seeds = false
skip-lint = false
[programs.localnet]
dindidoc = "HNhKbNom5uxSh87XJ6FwKDwP1CapZDhmRJLnmw4Ad52P"
[programs.devnet]
dindidoc = "HNhKbNom5uxSh87XJ6FwKDwP1CapZDhmRJLnmw4Ad52P"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/MansElfving/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
